# This is a basic workflow to help you get started with Actions1

name: cypress_tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
 
 #pull_request:
  # branches:
  #- master

jobs:
  cypress-run:        
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.13.0-chrome95-ff94
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
          
      - name: Cypress.io
        uses: cypress-io/github-action@v4.1.1
        continue-on-error: true
        with:
          spec: cypress/e2e/1-getting-started/todo.cy.js
          browser: chrome
          
          
          
      - name: Copy test execution videos and screenshots
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          cp -r cypress/screenshots public/screenshots
      - name: Merge test reports
        run: npm run combine:report

      - name: Generate HTML report
        run: npm run generate:report
      
      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          PUBLISH_BRANCH: gh-pages
      
